<?php

/**
 * @file
 * Contains google_kpis.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function google_kpis_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the google_kpis module.
    case 'help.page.google_kpis':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fetch and Store data from Google Analytics and Google Search Console') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function google_kpis_theme() {
  return [
    'google_kpis' => [
      'render element' => 'children',
    ],
  ];
}
